regions:
  port:
    region: port
    name: Порт
    time_to_capture: 10
    time_to_keep: 20
    min_clan_players: 1
    perm_to_set: clanbattle.captured
    player_payout: 100
    clan_payout_per_player: 100
    period: 60
    msg_prefix: "§6[§9Захват региона§6]§f"
    owner_suffix: "§6[§4АГРЕССОР§4]§f"
