name: PluginTemplate
description: "Plugin template."
version: 1.0
main: net.dinikin.plugin.PluginTemplate
depend: []
commands:
  pt:
    description: Plugin Template V1.0
  plugintemplate:
    description: Plugin Template V1.0
