name: ClanBattle
description: "Plugin allows clans to battle for regions."
version: 1.0
main: net.piratebayserver.plugin.ClanBattlePlugin
depend: [WorldGuard, Vault, LuckPerms, AdvancedClans, Essentials]
commands:
  cb:
    description: Clan Battle V1.0
  clanbattle:
    description: Clan Battle V1.0
